### ISSUE TITLE
What version of Unreal?

### ISSUE THREAD

**Issue by n1ckfg** [benmadany/PaintSpace#1]
Project can't be opened for me using 4.15; what version should I be using? Thanks!

**Comment by benmadany** [comment]
Hi,

Sorry for the delayed reply. At the time I built the project, 4.10 was the
latest version of Unreal, so you would need to use that. I appreciate your
interest in it, though unfortunately I haven't looked at the project in a
while, so I can't really provide much help in getting it running. There are
likely other projects out there that are better implementations than mine
and have done more impressive things with VR and 3D painting. I was
originally inspired partly by this Unity project:
https://jscottk.itch.io/graffiti-3d

There are also a few more recent ones, Google's Tiltbrush being one of the
most popular, but there are some others for Rift/Vive I believe. I'm not
too sure about open source options, though. If you've got other questions,
I can do my best to answer them, and good luck with anything you do using
VR/Unreal!

**Comment by n1ckfg** [comment]
Cool; thanks for that list of resources too!
